#include "pch.h"

// Dummy functions exported by this plugin to replace the 373 exported by xbdm
// when allowing debug builds to run on retail kernel.

// clang-format off

HRESULT StubExport1()   { return S_OK; }
HRESULT StubExport2()   { return S_OK; }
HRESULT StubExport3()   { return S_OK; }
HRESULT StubExport4()   { return S_OK; }
HRESULT StubExport5()   { return S_OK; }
HRESULT StubExport6()   { return S_OK; }
HRESULT StubExport7()   { return S_OK; }
HRESULT StubExport8()   { return S_OK; }
HRESULT StubExport9()   { return S_OK; }
HRESULT StubExport10()  { return S_OK; }
HRESULT StubExport11()  { return S_OK; }
HRESULT StubExport12()  { return S_OK; }
HRESULT StubExport13()  { return S_OK; }
HRESULT StubExport14()  { return S_OK; }
HRESULT StubExport15()  { return S_OK; }
HRESULT StubExport16()  { return S_OK; }
HRESULT StubExport17()  { return S_OK; }
HRESULT StubExport18()  { return S_OK; }
HRESULT StubExport19()  { return S_OK; }
HRESULT StubExport20()  { return S_OK; }
HRESULT StubExport21()  { return S_OK; }
HRESULT StubExport22()  { return S_OK; }
HRESULT StubExport23()  { return S_OK; }
HRESULT StubExport24()  { return S_OK; }
HRESULT StubExport25()  { return S_OK; }
HRESULT StubExport26()  { return S_OK; }
HRESULT StubExport27()  { return S_OK; }
HRESULT StubExport28()  { return S_OK; }
HRESULT StubExport29()  { return S_OK; }
HRESULT StubExport30()  { return S_OK; }
HRESULT StubExport31()  { return S_OK; }
HRESULT StubExport32()  { return S_OK; }
HRESULT StubExport33()  { return S_OK; }
HRESULT StubExport34()  { return S_OK; }
HRESULT StubExport35()  { return S_OK; }
HRESULT StubExport36()  { return S_OK; }
HRESULT StubExport37()  { return S_OK; }
HRESULT StubExport38()  { return S_OK; }
HRESULT StubExport39()  { return S_OK; }
HRESULT StubExport40()  { return S_OK; }
HRESULT StubExport41()  { return S_OK; }
HRESULT StubExport42()  { return S_OK; }
HRESULT StubExport43()  { return S_OK; }
HRESULT StubExport44()  { return S_OK; }
HRESULT StubExport45()  { return S_OK; }
HRESULT StubExport46()  { return S_OK; }
HRESULT StubExport47()  { return S_OK; }
HRESULT StubExport48()  { return S_OK; }
HRESULT StubExport49()  { return S_OK; }
HRESULT StubExport50()  { return S_OK; }
HRESULT StubExport51()  { return S_OK; }
HRESULT StubExport52()  { return S_OK; }
HRESULT StubExport53()  { return S_OK; }
HRESULT StubExport54()  { return S_OK; }
HRESULT StubExport55()  { return S_OK; }
HRESULT StubExport56()  { return S_OK; }
HRESULT StubExport57()  { return S_OK; }
HRESULT StubExport58()  { return S_OK; }
HRESULT StubExport59()  { return S_OK; }
HRESULT StubExport60()  { return S_OK; }
HRESULT StubExport61()  { return S_OK; }
HRESULT StubExport62()  { return S_OK; }
HRESULT StubExport63()  { return S_OK; }
HRESULT StubExport64()  { return S_OK; }
HRESULT StubExport65()  { return S_OK; }
HRESULT StubExport66()  { return S_OK; }
HRESULT StubExport67()  { return S_OK; }
HRESULT StubExport68()  { return S_OK; }
HRESULT StubExport69()  { return S_OK; }
HRESULT StubExport70()  { return S_OK; }
HRESULT StubExport71()  { return S_OK; }
HRESULT StubExport72()  { return S_OK; }
HRESULT StubExport73()  { return S_OK; }
HRESULT StubExport74()  { return S_OK; }
HRESULT StubExport75()  { return S_OK; }
HRESULT StubExport76()  { return S_OK; }
HRESULT StubExport77()  { return S_OK; }
HRESULT StubExport78()  { return S_OK; }
HRESULT StubExport79()  { return S_OK; }
HRESULT StubExport80()  { return S_OK; }
HRESULT StubExport81()  { return S_OK; }
HRESULT StubExport82()  { return S_OK; }
HRESULT StubExport83()  { return S_OK; }
HRESULT StubExport84()  { return S_OK; }
HRESULT StubExport85()  { return S_OK; }
HRESULT StubExport86()  { return S_OK; }
HRESULT StubExport87()  { return S_OK; }
HRESULT StubExport88()  { return S_OK; }
HRESULT StubExport89()  { return S_OK; }
HRESULT StubExport90()  { return S_OK; }
HRESULT StubExport91()  { return S_OK; }
HRESULT StubExport92()  { return S_OK; }
HRESULT StubExport93()  { return S_OK; }
HRESULT StubExport94()  { return S_OK; }
HRESULT StubExport95()  { return S_OK; }
HRESULT StubExport96()  { return S_OK; }
HRESULT StubExport97()  { return S_OK; }
HRESULT StubExport98()  { return S_OK; }
HRESULT StubExport99()  { return S_OK; }
HRESULT StubExport100() { return S_OK; }
HRESULT StubExport101() { return S_OK; }
HRESULT StubExport102() { return S_OK; }
HRESULT StubExport103() { return S_OK; }
HRESULT StubExport104() { return S_OK; }
HRESULT StubExport105() { return S_OK; }
HRESULT StubExport106() { return S_OK; }
HRESULT StubExport107() { return S_OK; }
HRESULT StubExport108() { return S_OK; }
HRESULT StubExport109() { return S_OK; }
HRESULT StubExport110() { return S_OK; }
HRESULT StubExport111() { return S_OK; }
HRESULT StubExport112() { return S_OK; }
HRESULT StubExport113() { return S_OK; }
HRESULT StubExport114() { return S_OK; }
HRESULT StubExport115() { return S_OK; }
HRESULT StubExport116() { return S_OK; }
HRESULT StubExport117() { return S_OK; }
HRESULT StubExport118() { return S_OK; }
HRESULT StubExport119() { return S_OK; }
HRESULT StubExport120() { return S_OK; }
HRESULT StubExport121() { return S_OK; }
HRESULT StubExport122() { return S_OK; }
HRESULT StubExport123() { return S_OK; }
HRESULT StubExport124() { return S_OK; }
HRESULT StubExport125() { return S_OK; }
HRESULT StubExport126() { return S_OK; }
HRESULT StubExport127() { return S_OK; }
HRESULT StubExport128() { return S_OK; }
HRESULT StubExport129() { return S_OK; }
HRESULT StubExport130() { return S_OK; }
HRESULT StubExport131() { return S_OK; }
HRESULT StubExport132() { return S_OK; }
HRESULT StubExport133() { return S_OK; }
HRESULT StubExport134() { return S_OK; }
HRESULT StubExport135() { return S_OK; }
HRESULT StubExport136() { return S_OK; }
HRESULT StubExport137() { return S_OK; }
HRESULT StubExport138() { return S_OK; }
HRESULT StubExport139() { return S_OK; }
HRESULT StubExport140() { return S_OK; }
HRESULT StubExport141() { return S_OK; }
HRESULT StubExport142() { return S_OK; }
HRESULT StubExport143() { return S_OK; }
HRESULT StubExport144() { return S_OK; }
HRESULT StubExport145() { return S_OK; }
HRESULT StubExport146() { return S_OK; }
HRESULT StubExport147() { return S_OK; }
HRESULT StubExport148() { return S_OK; }
HRESULT StubExport149() { return S_OK; }
HRESULT StubExport150() { return S_OK; }
HRESULT StubExport151() { return S_OK; }
HRESULT StubExport152() { return S_OK; }
HRESULT StubExport153() { return S_OK; }
HRESULT StubExport154() { return S_OK; }
HRESULT StubExport155() { return S_OK; }
HRESULT StubExport156() { return S_OK; }
HRESULT StubExport157() { return S_OK; }
HRESULT StubExport158() { return S_OK; }
HRESULT StubExport159() { return S_OK; }
HRESULT StubExport160() { return S_OK; }
HRESULT StubExport161() { return S_OK; }
HRESULT StubExport162() { return S_OK; }
HRESULT StubExport163() { return S_OK; }
HRESULT StubExport164() { return S_OK; }
HRESULT StubExport165() { return S_OK; }
HRESULT StubExport166() { return S_OK; }
HRESULT StubExport167() { return S_OK; }
HRESULT StubExport168() { return S_OK; }
HRESULT StubExport169() { return S_OK; }
HRESULT StubExport170() { return S_OK; }
HRESULT StubExport171() { return S_OK; }
HRESULT StubExport172() { return S_OK; }
HRESULT StubExport173() { return S_OK; }
HRESULT StubExport174() { return S_OK; }
HRESULT StubExport175() { return S_OK; }
HRESULT StubExport176() { return S_OK; }
HRESULT StubExport177() { return S_OK; }
HRESULT StubExport178() { return S_OK; }
HRESULT StubExport179() { return S_OK; }
HRESULT StubExport180() { return S_OK; }
HRESULT StubExport181() { return S_OK; }
HRESULT StubExport182() { return S_OK; }
HRESULT StubExport183() { return S_OK; }
HRESULT StubExport184() { return S_OK; }
HRESULT StubExport185() { return S_OK; }
HRESULT StubExport186() { return S_OK; }
HRESULT StubExport187() { return S_OK; }
HRESULT StubExport188() { return S_OK; }
HRESULT StubExport189() { return S_OK; }
HRESULT StubExport190() { return S_OK; }
HRESULT StubExport191() { return S_OK; }
HRESULT StubExport192() { return S_OK; }
HRESULT StubExport193() { return S_OK; }
HRESULT StubExport194() { return S_OK; }
HRESULT StubExport195() { return S_OK; }
HRESULT StubExport196() { return S_OK; }
HRESULT StubExport197() { return S_OK; }
HRESULT StubExport198() { return S_OK; }
HRESULT StubExport199() { return S_OK; }
HRESULT StubExport200() { return S_OK; }
HRESULT StubExport201() { return S_OK; }
HRESULT StubExport202() { return S_OK; }
HRESULT StubExport203() { return S_OK; }
HRESULT StubExport204() { return S_OK; }
HRESULT StubExport205() { return S_OK; }
HRESULT StubExport206() { return S_OK; }
HRESULT StubExport207() { return S_OK; }
HRESULT StubExport208() { return S_OK; }
HRESULT StubExport209() { return S_OK; }
HRESULT StubExport210() { return S_OK; }
HRESULT StubExport211() { return S_OK; }
HRESULT StubExport212() { return S_OK; }
HRESULT StubExport213() { return S_OK; }
HRESULT StubExport214() { return S_OK; }
HRESULT StubExport215() { return S_OK; }
HRESULT StubExport216() { return S_OK; }
HRESULT StubExport217() { return S_OK; }
HRESULT StubExport218() { return S_OK; }
HRESULT StubExport219() { return S_OK; }
HRESULT StubExport220() { return S_OK; }
HRESULT StubExport221() { return S_OK; }
HRESULT StubExport222() { return S_OK; }
HRESULT StubExport223() { return S_OK; }
HRESULT StubExport224() { return S_OK; }
HRESULT StubExport225() { return S_OK; }
HRESULT StubExport226() { return S_OK; }
HRESULT StubExport227() { return S_OK; }
HRESULT StubExport228() { return S_OK; }
HRESULT StubExport229() { return S_OK; }
HRESULT StubExport230() { return S_OK; }
HRESULT StubExport231() { return S_OK; }
HRESULT StubExport232() { return S_OK; }
HRESULT StubExport233() { return S_OK; }
HRESULT StubExport234() { return S_OK; }
HRESULT StubExport235() { return S_OK; }
HRESULT StubExport236() { return S_OK; }
HRESULT StubExport237() { return S_OK; }
HRESULT StubExport238() { return S_OK; }
HRESULT StubExport239() { return S_OK; }
HRESULT StubExport240() { return S_OK; }
HRESULT StubExport241() { return S_OK; }
HRESULT StubExport242() { return S_OK; }
HRESULT StubExport243() { return S_OK; }
HRESULT StubExport244() { return S_OK; }
HRESULT StubExport245() { return S_OK; }
HRESULT StubExport246() { return S_OK; }
HRESULT StubExport247() { return S_OK; }
HRESULT StubExport248() { return S_OK; }
HRESULT StubExport249() { return S_OK; }
HRESULT StubExport250() { return S_OK; }
HRESULT StubExport251() { return S_OK; }
HRESULT StubExport252() { return S_OK; }
HRESULT StubExport253() { return S_OK; }
HRESULT StubExport254() { return S_OK; }
HRESULT StubExport255() { return S_OK; }
HRESULT StubExport256() { return S_OK; }
HRESULT StubExport257() { return S_OK; }
HRESULT StubExport258() { return S_OK; }
HRESULT StubExport259() { return S_OK; }
HRESULT StubExport260() { return S_OK; }
HRESULT StubExport261() { return S_OK; }
HRESULT StubExport262() { return S_OK; }
HRESULT StubExport263() { return S_OK; }
HRESULT StubExport264() { return S_OK; }
HRESULT StubExport265() { return S_OK; }
HRESULT StubExport266() { return S_OK; }
HRESULT StubExport267() { return S_OK; }
HRESULT StubExport268() { return S_OK; }
HRESULT StubExport269() { return S_OK; }
HRESULT StubExport270() { return S_OK; }
HRESULT StubExport271() { return S_OK; }
HRESULT StubExport272() { return S_OK; }
HRESULT StubExport273() { return S_OK; }
HRESULT StubExport274() { return S_OK; }
HRESULT StubExport275() { return S_OK; }
HRESULT StubExport276() { return S_OK; }
HRESULT StubExport277() { return S_OK; }
HRESULT StubExport278() { return S_OK; }
HRESULT StubExport279() { return S_OK; }
HRESULT StubExport280() { return S_OK; }
HRESULT StubExport281() { return S_OK; }
HRESULT StubExport282() { return S_OK; }
HRESULT StubExport283() { return S_OK; }
HRESULT StubExport284() { return S_OK; }
HRESULT StubExport285() { return S_OK; }
HRESULT StubExport286() { return S_OK; }
HRESULT StubExport287() { return S_OK; }
HRESULT StubExport288() { return S_OK; }
HRESULT StubExport289() { return S_OK; }
HRESULT StubExport290() { return S_OK; }
HRESULT StubExport291() { return S_OK; }
HRESULT StubExport292() { return S_OK; }
HRESULT StubExport293() { return S_OK; }
HRESULT StubExport294() { return S_OK; }
HRESULT StubExport295() { return S_OK; }
HRESULT StubExport296() { return S_OK; }
HRESULT StubExport297() { return S_OK; }
HRESULT StubExport298() { return S_OK; }
HRESULT StubExport299() { return S_OK; }
HRESULT StubExport300() { return S_OK; }
HRESULT StubExport301() { return S_OK; }
HRESULT StubExport302() { return S_OK; }
HRESULT StubExport303() { return S_OK; }
HRESULT StubExport304() { return S_OK; }
HRESULT StubExport305() { return S_OK; }
HRESULT StubExport306() { return S_OK; }
HRESULT StubExport307() { return S_OK; }
HRESULT StubExport308() { return S_OK; }
HRESULT StubExport309() { return S_OK; }
HRESULT StubExport310() { return S_OK; }
HRESULT StubExport311() { return S_OK; }
HRESULT StubExport312() { return S_OK; }
HRESULT StubExport313() { return S_OK; }
HRESULT StubExport314() { return S_OK; }
HRESULT StubExport315() { return S_OK; }
HRESULT StubExport316() { return S_OK; }
HRESULT StubExport317() { return S_OK; }
HRESULT StubExport318() { return S_OK; }
HRESULT StubExport319() { return S_OK; }
HRESULT StubExport320() { return S_OK; }
HRESULT StubExport321() { return S_OK; }
HRESULT StubExport322() { return S_OK; }
HRESULT StubExport323() { return S_OK; }
HRESULT StubExport324() { return S_OK; }
HRESULT StubExport325() { return S_OK; }
HRESULT StubExport326() { return S_OK; }
HRESULT StubExport327() { return S_OK; }
HRESULT StubExport328() { return S_OK; }
HRESULT StubExport329() { return S_OK; }
HRESULT StubExport330() { return S_OK; }
HRESULT StubExport331() { return S_OK; }
HRESULT StubExport332() { return S_OK; }
HRESULT StubExport333() { return S_OK; }
HRESULT StubExport334() { return S_OK; }
HRESULT StubExport335() { return S_OK; }
HRESULT StubExport336() { return S_OK; }
HRESULT StubExport337() { return S_OK; }
HRESULT StubExport338() { return S_OK; }
HRESULT StubExport339() { return S_OK; }
HRESULT StubExport340() { return S_OK; }
HRESULT StubExport341() { return S_OK; }
HRESULT StubExport342() { return S_OK; }
HRESULT StubExport343() { return S_OK; }
HRESULT StubExport344() { return S_OK; }
HRESULT StubExport345() { return S_OK; }
HRESULT StubExport346() { return S_OK; }
HRESULT StubExport347() { return S_OK; }
HRESULT StubExport348() { return S_OK; }
HRESULT StubExport349() { return S_OK; }
HRESULT StubExport350() { return S_OK; }
HRESULT StubExport351() { return S_OK; }
HRESULT StubExport352() { return S_OK; }
HRESULT StubExport353() { return S_OK; }
HRESULT StubExport354() { return S_OK; }
HRESULT StubExport355() { return S_OK; }
HRESULT StubExport356() { return S_OK; }
HRESULT StubExport357() { return S_OK; }
HRESULT StubExport358() { return S_OK; }
HRESULT StubExport359() { return S_OK; }
HRESULT StubExport360() { return S_OK; }
HRESULT StubExport361() { return S_OK; }
HRESULT StubExport362() { return S_OK; }
HRESULT StubExport363() { return S_OK; }
HRESULT StubExport364() { return S_OK; }
HRESULT StubExport365() { return S_OK; }
HRESULT StubExport366() { return S_OK; }
HRESULT StubExport367() { return S_OK; }
HRESULT StubExport368() { return S_OK; }
HRESULT StubExport369() { return S_OK; }
HRESULT StubExport370() { return S_OK; }
HRESULT StubExport371() { return S_OK; }
HRESULT StubExport372() { return S_OK; }
HRESULT StubExport373() { return S_OK; }

// clang-format on
