name: Check code formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-code-formatting:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check code formatting with clang-format.
        uses: jidicula/clang-format-action@v4.14.0
        with:
          clang-format-version: 19
          check-path: src
